architecture: minicpm
model_path: openbmb/MiniCPM-o-2_6
model:
  - torch_dtype: auto
  - trust_remote_code: True
  - attn_implementation: sdpa
forward:
  - max_new_tokens: 1
output_db: output/minicpm-o.db
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
modules:
  - llm.lm_head
  - vpm.encoder.layers.26
