architecture: internlm-xcomposer
model_path: internlm/internlm-xcomposer2d5-7b
model:
  - torch_dtype: auto
  - attn_implementation: eager
forward:
  - max_new_tokens: 1
output_db: output/internlm.db
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
modules:
  - model.layers.31
  - vit.vision_tower.vision_model.encoder.layers.23
