architecture: minicpm
model_path: wonderwind271/MiniCPM-V-2
dataset:
  - text_dataset_path: wonderwind271/CLEVR_val_categories
  - image_dataset_path: /path/to/your/CLEVR/CLEVR_v1.0/images  # CHANGE ME
  - text_split: material
  - image_split: val
  - prompt_column: Q
  - label_column: A
  - image_column: image_filename
model:
  - torch_dtype: auto
  - trust_remote_code: True
forward:
  - max_new_tokens: 1
output_db: minicpm-V2-material.db
pooled_output: True
modules:
  - llm.model.layers.19.post_attention_layernorm
  - llm.model.layers.39.post_attention_layernorm
