architecture: blip2
model_path: Salesforce/blip2-opt-2.7b
dataset:
  - text_dataset_path: compling/CLEVR_val_categories
  - image_dataset_path: /scratch/chaijy_root/chaijy2/shuyuwu/data/CLEVR/images/CLEVR_v1.0/images  # downloaded using configs/dataset/clevr.yaml
  - text_split: shape
  - image_split: val
  - prompt_column: Q
  - label_column: A
  - image_column: image_filename
output_db: /scratch/chaijy_root/chaijy2/shuyuwu/compling/blip2_shape.db
pooled_output: True
modules:
  - language_model.model.decoder.layers.16.self_attn_layer_norm
  - language_model.model.decoder.layers.31.self_attn_layer_norm
