architecture: pixtral
model_path: mistralai/Pixtral-12B-2409
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
output_db: output/Pixtral-12B-2409.db
modules:
  - layers.19.attention_norm
  - layers.39.attention_norm
download_path: "/project/aip-fredashi/fredashi/huggingface/pixtral-12b" # CHANGE THIS. This is the path to store the downloaded model. This dir will be created.
