architecture: molmo
model_path: allenai/Molmo-7B-D-0924
model:
  - torch_dtype: auto
forward:
  - max_new_tokens: 1
  - stop_strings: <|endoftext|>
output_db: output/molmo.db
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
modules:
  - model.transformer.blocks.0
  - model.vision_backbone.image_vit.transformer.resblocks.22
