architecture: blip2
model_path: Salesforce/blip2-opt-2.7b
model:
  - torch_dtype: auto
output_db: blip2.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - language_model.lm_head
  - vision_model.post_layernorm
