architecture: janus
model_path: deepseek-ai/Janus-Pro-7B
model:
  - torch_dtype: auto
output_db: janus1d3b.db
input_dir: ./data
prompt: "Describe the color in this image in one word."
modules:
  - language_model.lm_head
  - vision_model.vision_tower.blocks.0.attn.qkv
  - vision_model.vision_tower.blocks.0.mlp.fc1
  - vision_model.vision_tower.blocks.0.mlp.fc2
