architecture: minicpm
model_path: openbmb/MiniCPM-o-2_6
dataset:
  - text_dataset_path: wonderwind271/CLEVR_val_categories
  - image_dataset_path: /path/to/your/CLEVR/CLEVR_v1.0/images  # CHANGE ME
  - text_split: number
  - image_split: val
  - prompt_column: Q
  - label_column: A
  - image_column: image_filename
forward:
  - max_new_tokens: 1
output_db: minicpm-o-number.db
model:
  - torch_dtype: auto
  - trust_remote_code: True
  - attn_implementation: sdpa
pooled_output: True
modules:
  - llm.model.layers.13.post_attention_layernorm
  - llm.model.layers.27.post_attention_layernorm

